title: "Akinyemi Afolabi"
author: "Akinyemi Afolabi"
description: "My blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "home", sidebaricon: address-card}
  - {file: "AkinyemiAfolabi_CV.pdf", title: "CV", sidebaricon: address-card}
  - {file: "Publications", title: "Publications", sidebaricon: address-card}
  - {file: "Awards and Honors", title: "Awards and Honors", sidebaricon: address-card}
  - {file: "blog.md", title:"Blog", sidebaricon: home}
  - {file: "Work.md", title: "works", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:afolabiakinyemi@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/chrisbillakings"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
